<?php 

//$prefix =  $this->baseUrl();
	  $prefix =  $_SERVER['SCRIPT_NAME'];

?><pre><?php 
//var_dump($_SERVER);

?>
</pre>




<p>What do you want to do? </p>

<ul>

<li><a href="/campaigns/index/companies">Create a campaign</a></li>
<li><a href="<?php echo $prefix;?>/campaigns/index/companies">Create a campaign</a></li>
<li><a href="<?php echo $prefix;?>/admin/index/create">Add a user</a></li>
<li><a href="<?php echo $prefix;?>/campaigns/index/companies">Upload an Image</a></li>
<li><a href="<?php echo $prefix;?>/alerts/index/create">Generate an alert</a></li>
<li><a href="<?php echo $prefix;?>/campaigns/index/createcompany">Add a company</a></li>

</ul>






